#version 430

layout (local_size_x = 32, local_size_y = 32) in;
layout (binding = 0, rgba8) uniform image2D resultImage;

layout (push_constant) uniform Constants {
    vec2 iMouse;
    float iTime;
} constants;

const vec2 iResolution = vec2(1280, 720);

void main() {
    ivec2 iuv = ivec2(gl_GlobalInvocationID.xy);
    vec2 uv = iuv / iResolution.xy;
    vec3 result = normalize(vec3(uv.x, constants.iTime, uv.y));
    imageStore(resultImage, iuv, vec4(result, 0.0));
}